import assert from "node:assert/strict";
import test from "node:test";

import { getPneumoniaDemoProfile } from "../src/pneumonia-demo-data.js";

const PROFILE_IDS = ["demo-patient-kim", "demo-patient-choi", "demo-patient-jung"];
const PERIOD = { start: "2026-10-01", end: "2027-03-31" };

function profiles() {
  return PROFILE_IDS.map((id) => getPneumoniaDemoProfile(id));
}

function hoursBetween(after, before) {
  return (Date.parse(after) - Date.parse(before)) / 3_600_000;
}

function patientMetricTruth(profile) {
  const arrival = profile.admission.arrivedAt;
  const firstIv = profile.medicationAdministrations
    .filter(({ route, status }) => route === "IV" && status === "COMPLETED")
    .sort((left, right) => Date.parse(left.administeredAt) - Date.parse(right.administeredAt))[0];
  const blood = profile.specimenCollections.find(({ kind }) => kind === "BLOOD_CULTURE");
  return {
    oxygenWithin24Hours: profile.observations.some(({ kind, recordedAt }) => (
      kind === "OXYGEN_SATURATION" && hoursBetween(recordedAt, arrival) >= 0 && hoursBetween(recordedAt, arrival) <= 24
    )),
    severityWithin24Hours: profile.severityAssessments.some(({ tool, assessedAt }) => (
      ["CURB-65", "PSI"].includes(tool) && hoursBetween(assessedAt, arrival) >= 0 && hoursBetween(assessedAt, arrival) <= 24
    )),
    sputumCultureWithin24Hours: profile.microbiologyOrders.some(({ kind, orderedAt }) => (
      kind === "SPUTUM_CULTURE" && hoursBetween(orderedAt, arrival) >= 0 && hoursBetween(orderedAt, arrival) <= 24
    )),
    bloodCultureBeforeFirstIv: Boolean(blood && firstIv && Date.parse(blood.collectedAt) < Date.parse(firstIv.administeredAt)),
    appropriateFirstIvWithin8Hours: Boolean(
      firstIv
      && firstIv.appropriateForCap === true
      && firstIv.appropriatenessReview?.status === "APPROPRIATE"
      && hoursBetween(firstIv.administeredAt, arrival) >= 0
      && hoursBetween(firstIv.administeredAt, arrival) <= 8,
    ),
  };
}

function verified(provenance) {
  return provenance?.verificationStatus === "VERIFIED"
    && provenance?.patientMatch === "VERIFIED"
    && Boolean(provenance?.sourceId)
    && Boolean(provenance?.reviewerId)
    && Number.isFinite(Date.parse(provenance?.verifiedAt));
}

test("김비타·최민아·정수진 예시 환자에게만 의사용 합성 폐렴 프로필을 연결한다", () => {
  assert.deepEqual(
    profiles().map(({ patient }) => [patient.id, patient.name]),
    [
      ["demo-patient-kim", "김비타"],
      ["demo-patient-choi", "최민아"],
      ["demo-patient-jung", "정수진"],
    ],
  );

  for (const profile of profiles()) {
    assert.equal(profile.schema, "vitagraph-pneumonia-demo-profile");
    assert.equal(profile.physicianOnly, true);
    assert.equal(profile.synthetic, true);
    assert.match(profile.syntheticNotice, /예시 환자/);
    assert.match(profile.syntheticNotice, /실제 환자 아님/);
    assert.match(profile.syntheticNotice, /공식 심사결과 아님/);
    assert.doesNotMatch(profile.syntheticNotice, /\bcontest\b|공모전|데모|\bDEMO\b/i);
    assert.deepEqual(profile.evaluationPeriod, PERIOD);
    assert.ok(Object.values(profile.ruleVersions).every(Boolean));
    assert.ok(Number.isFinite(Date.parse(profile.evaluatedAt)));
  }

  assert.equal(getPneumoniaDemoProfile("demo-patient-lee"), null);
  assert.equal(getPneumoniaDemoProfile({ id: "not-a-demo-patient" }), null);
  assert.equal(getPneumoniaDemoProfile(null), null);
});

test("세 프로필은 J18.9 지역사회획득 폐렴 입원과 3일 이상 정맥 항생제 흐름을 가진다", () => {
  for (const profile of profiles()) {
    assert.equal(profile.admission.setting, "INPATIENT");
    assert.equal(profile.admission.institutionType, "GENERAL_HOSPITAL");
    assert.equal(profile.admission.communityOnset, true);
    assert.equal(profile.admission.diagnosedWithin48Hours, true);
    assert.ok(profile.admission.diagnosedWithinHours >= 0 && profile.admission.diagnosedWithinHours <= 48);
    assert.ok(profile.admission.ivAntibioticDays >= 3);
    assert.ok(Date.parse(profile.admission.arrivedAt) < Date.parse(profile.admission.dischargedAt));

    assert.equal(profile.diagnoses.length, 1);
    assert.equal(profile.diagnoses[0].code, "J18.9");
    assert.equal(profile.diagnoses[0].status, "CLINICIAN_CONFIRMED");
    assert.equal(profile.diagnoses[0].autoGenerated, false);
    assert.equal(profile.diagnoses[0].encounterId, profile.admission.id);

    assert.equal(profile.clinicalContext.evidenceStatus, "VERIFIED");
    assert.ok(profile.clinicalContext.symptoms.length >= 2);
    assert.equal(profile.clinicalContext.communityAcquired.confirmed, true);
    assert.equal(profile.clinicalContext.communityAcquired.diagnosedWithin48Hours, true);
    assert.ok(profile.clinicalContext.chestImaging.some(({ status, supportsPneumonia }) => status === "FINAL" && supportsPneumonia));

    const ivDates = new Set(profile.medicationAdministrations
      .filter(({ route, status }) => route === "IV" && status === "COMPLETED")
      .map(({ administeredAt }) => administeredAt.slice(0, 10)));
    assert.equal(ivDates.size, profile.admission.ivAntibioticDays);
    assert.ok(profile.medicationAdministrations.some(({ firstDose, appropriateForCap }) => firstDose && appropriateForCap));
  }
});

test("김비타는 다섯 초기 적정성 확인 항목이 모두 충족되는 완전 사례다", () => {
  const profile = getPneumoniaDemoProfile("demo-patient-kim");
  const truth = patientMetricTruth(profile);

  assert.equal(profile.scenario.kind, "COMPLETE");
  assert.deepEqual(Object.values(truth), [true, true, true, true, true]);
  assert.equal(Object.values(truth).filter(Boolean).length, 5);
  assert.equal(profile.admission.ivAntibioticDays, 5);
  assert.equal(profile.severityAssessments[0].tool, "CURB-65");
  assert.equal(profile.specimenCollections[0].beforeFirstIvAntibiotic, true);
});

test("최민아는 혈액배양이 첫 정맥 항생제 뒤라 해당 항목만 충족되지 않는다", () => {
  const profile = getPneumoniaDemoProfile("demo-patient-choi");
  const truth = patientMetricTruth(profile);
  const blood = profile.specimenCollections[0];
  const firstIv = profile.medicationAdministrations.find(({ firstDose }) => firstDose);

  assert.equal(profile.scenario.kind, "BLOOD_CULTURE_AFTER_ANTIBIOTIC");
  assert.equal(truth.bloodCultureBeforeFirstIv, false);
  assert.equal(Object.values(truth).filter(Boolean).length, 4);
  assert.ok(Date.parse(blood.collectedAt) > Date.parse(firstIv.administeredAt));
  assert.equal(blood.beforeFirstIvAntibiotic, false);
  assert.equal(profile.admission.ivAntibioticDays, 4);
});

test("정수진은 중증도 도구만 누락되고 나머지 네 초기 항목은 확인된다", () => {
  const profile = getPneumoniaDemoProfile("demo-patient-jung");
  const truth = patientMetricTruth(profile);

  assert.equal(profile.scenario.kind, "MISSING_SEVERITY");
  assert.deepEqual(profile.severityAssessments, []);
  assert.equal(truth.severityWithin24Hours, false);
  assert.equal(Object.values(truth).filter(Boolean).length, 4);
  assert.equal(profile.specimenCollections[0].beforeFirstIvAntibiotic, true);
  assert.equal(profile.admission.ivAntibioticDays, 4);
});

test("청구 예시는 지정된 초록·노랑·회색 분포만 가지며 빨강이나 심사결정이 없다", () => {
  const expected = {
    "demo-patient-kim": { GREEN: 2, YELLOW: 0, GRAY: 1 },
    "demo-patient-choi": { GREEN: 1, YELLOW: 1, GRAY: 1 },
    "demo-patient-jung": { GREEN: 2, YELLOW: 0, GRAY: 1 },
  };

  for (const profile of profiles()) {
    const counts = { GREEN: 0, YELLOW: 0, GRAY: 0 };
    for (const item of profile.claimItems) {
      assert.ok(["GREEN", "YELLOW", "GRAY"].includes(item.preflight.status));
      assert.notEqual(item.preflight.status, "RED");
      assert.equal(item.physicianOnly, true);
      assert.equal(item.synthetic, true);
      assert.match(item.preflight.disclaimer, /지급 보장 아님|삭감 확정 아님|삭감 확정을 의미하지 않음|삭감 확정이 아님/);
      counts[item.preflight.status] += 1;
    }
    assert.deepEqual(counts, expected[profile.patient.id]);
    assert.deepEqual(profile.adjudications, []);
  }
});

test("진단·임상 맥락·검사·투약은 식별 가능한 검증 출처를 가진다", () => {
  for (const profile of profiles()) {
    const evidence = [
      profile.admission,
      ...profile.diagnoses,
      ...profile.clinicalContext.symptoms,
      ...profile.clinicalContext.chestImaging,
      profile.clinicalContext.communityAcquired,
      ...profile.observations,
      ...profile.severityAssessments,
      ...profile.microbiologyOrders,
      ...profile.specimenCollections,
      ...profile.medicationAdministrations,
      ...profile.claimItems,
    ];
    for (const item of evidence) assert.equal(verified(item.provenance), true, item.id ?? item.code ?? "clinical context");
  }
});

test("호출마다 깊은 복제본을 반환해 다른 환자 화면과 합성 원본을 오염시키지 않는다", () => {
  const first = getPneumoniaDemoProfile("demo-patient-kim");
  const second = getPneumoniaDemoProfile({ id: "demo-patient-kim" });

  assert.notEqual(first, second);
  assert.notEqual(first.patient, second.patient);
  assert.notEqual(first.admission, second.admission);
  assert.notEqual(first.clinicalContext.chestImaging, second.clinicalContext.chestImaging);
  assert.notEqual(first.medicationAdministrations[0].provenance, second.medicationAdministrations[0].provenance);

  first.patient.name = "변경된 이름";
  first.admission.ivAntibioticDays = 0;
  first.clinicalContext.chestImaging[0].finding = "변경";
  first.medicationAdministrations[0].provenance.sourceId = "mutated";
  first.claimItems[0].preflight.status = "RED";

  const fresh = getPneumoniaDemoProfile("demo-patient-kim");
  assert.equal(fresh.patient.name, "김비타");
  assert.equal(fresh.admission.ivAntibioticDays, 5);
  assert.match(fresh.clinicalContext.chestImaging[0].finding, /우하엽/);
  assert.equal(fresh.medicationAdministrations[0].provenance.sourceId, "kim-pna-ceftriaxone-day1-administration");
  assert.equal(fresh.claimItems[0].preflight.status, "GREEN");
});
