import { mkdir, readFile, rm, writeFile } from "node:fs/promises";

const cssAssets = [
  "foundation",
  "controls",
  "body-map",
  "graph",
  "detail",
  "responsive",
].map((name) => ({
  route: `/${name}.css`,
  file: `src/${name}.css`,
  type: "text/css; charset=utf-8",
}));

const sourceAssets = [
  { route: "/", file: "src/index.html", type: "text/html; charset=utf-8" },
  ...cssAssets,
  { route: "/data.js", file: "src/data.js", type: "text/javascript; charset=utf-8" },
  { route: "/view-model.js", file: "src/view-model.js", type: "text/javascript; charset=utf-8" },
  { route: "/app.js", file: "src/app.js", type: "text/javascript; charset=utf-8" },
];

const entries = await Promise.all(
  sourceAssets.map(async ({ route, file, type }) => [
    route,
    { body: await readFile(file, "utf8"), type },
  ]),
);

const assets = Object.fromEntries(entries);
const workerSource = `// Generated by scripts/build.mjs. Source lives in src/.
const assets = ${JSON.stringify(assets)};
const baseHeaders = {
  "cache-control": "no-store",
  "content-security-policy": "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",
  "permissions-policy": "camera=(), microphone=(), geolocation=()",
  "referrer-policy": "no-referrer",
  "x-content-type-options": "nosniff",
  "x-frame-options": "DENY"
};

export default {
  async fetch(request) {
    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method not allowed", {
        status: 405,
        headers: { ...baseHeaders, allow: "GET, HEAD" }
      });
    }

    const url = new URL(request.url);
    const route = url.pathname === "/index.html" ? "/" : url.pathname;
    const asset = assets[route];
    if (!asset) {
      return new Response("Not found", { status: 404, headers: baseHeaders });
    }

    return new Response(request.method === "HEAD" ? null : asset.body, {
      headers: { ...baseHeaders, "content-type": asset.type }
    });
  }
};
`;

await rm("dist", { recursive: true, force: true });
await mkdir("dist/server", { recursive: true });
await writeFile("dist/server/index.js", workerSource, "utf8");
console.log("Built dist/server/index.js");
