import { mkdir, readFile, rm, writeFile } from "node:fs/promises";

const cssAssets = [
  "foundation",
  "shell",
  "controls",
  "body-map",
  "body-index",
  "portal",
  "detail",
  "responsive",
  "explorer",
  "journey",
  "brand-signals",
  "clinician-hierarchy",
  "patient-presentation",
  "landing",
  "gateway",
  "insights",
  "emr",
].map((name) => ({
  route: `/${name}.css`,
  file: `src/${name}.css`,
  type: "text/css; charset=utf-8",
}));

const sourceAssets = [
  { route: "/", file: "src/gateway.html", type: "text/html; charset=utf-8" },
  { route: "/patient", file: "src/landing.html", type: "text/html; charset=utf-8" },
  { route: "/patient.html", file: "src/landing.html", type: "text/html; charset=utf-8" },
  { route: "/map", file: "src/index.html", type: "text/html; charset=utf-8" },
  { route: "/map.html", file: "src/index.html", type: "text/html; charset=utf-8" },
  { route: "/connections", file: "src/connections.html", type: "text/html; charset=utf-8" },
  { route: "/connections.html", file: "src/connections.html", type: "text/html; charset=utf-8" },
  { route: "/journey", file: "src/journey.html", type: "text/html; charset=utf-8" },
  { route: "/journey.html", file: "src/journey.html", type: "text/html; charset=utf-8" },
  { route: "/insights", file: "src/insights.html", type: "text/html; charset=utf-8" },
  { route: "/insights.html", file: "src/insights.html", type: "text/html; charset=utf-8" },
  { route: "/emr", file: "src/emr.html", type: "text/html; charset=utf-8" },
  { route: "/emr.html", file: "src/emr.html", type: "text/html; charset=utf-8" },
  ...cssAssets,
  { route: "/data.js", file: "src/data.js", type: "text/javascript; charset=utf-8" },
  { route: "/view-model.js", file: "src/view-model.js", type: "text/javascript; charset=utf-8" },
  { route: "/app.js", file: "src/app.js", type: "text/javascript; charset=utf-8" },
  { route: "/explorer-model.js", file: "src/explorer-model.js", type: "text/javascript; charset=utf-8" },
  { route: "/connections.js", file: "src/connections.js", type: "text/javascript; charset=utf-8" },
  { route: "/journey-model.js", file: "src/journey-model.js", type: "text/javascript; charset=utf-8" },
  { route: "/journey.js", file: "src/journey.js", type: "text/javascript; charset=utf-8" },
  { route: "/insights.js", file: "src/insights.js", type: "text/javascript; charset=utf-8" },
  { route: "/insight-model.js", file: "src/insight-model.js", type: "text/javascript; charset=utf-8" },
  { route: "/patient-transfer.js", file: "src/patient-transfer.js", type: "text/javascript; charset=utf-8" },
  { route: "/care-bridge.js", file: "src/care-bridge.js", type: "text/javascript; charset=utf-8" },
  { route: "/patient-question-assistant.js", file: "src/patient-question-assistant.js", type: "text/javascript; charset=utf-8" },
  { route: "/landing.js", file: "src/landing.js", type: "text/javascript; charset=utf-8" },
  { route: "/emr.js", file: "src/emr.js", type: "text/javascript; charset=utf-8" },
  { route: "/emr-model.js", file: "src/emr-model.js", type: "text/javascript; charset=utf-8" },
  { route: "/clinical-question-assistant.js", file: "src/clinical-question-assistant.js", type: "text/javascript; charset=utf-8" },
  { route: "/emr-encounter.js", file: "src/emr-encounter.js", type: "text/javascript; charset=utf-8" },
  { route: "/emr-sign-review.js", file: "src/emr-sign-review.js", type: "text/javascript; charset=utf-8" },
  { route: "/emr-fhir.js", file: "src/emr-fhir.js", type: "text/javascript; charset=utf-8" },
  { route: "/emr-fhir-export.js", file: "src/emr-fhir-export.js", type: "text/javascript; charset=utf-8" },
  { route: "/clinical-observations.js", file: "src/clinical-observations.js", type: "text/javascript; charset=utf-8" },
  { route: "/claim-rules.js", file: "src/claim-rules.js", type: "text/javascript; charset=utf-8" },
];

const binaryAssets = [
  {
    route: "/assets/visit-prep-hero.png",
    file: "src/assets/visit-prep-hero.png",
    type: "image/png",
  },
  {
    route: "/assets/clinical-workspace-empty.png",
    file: "src/assets/clinical-workspace-empty.png",
    type: "image/png",
  },
  {
    route: "/assets/patient-journey-bridge.webp",
    file: "src/assets/patient-journey-bridge.webp",
    type: "image/webp",
  },
  {
    route: "/assets/body-atlas-v4.webp",
    file: "src/assets/body-atlas-v4.webp",
    type: "image/webp",
  },
];

const sourceEntries = await Promise.all(
  sourceAssets.map(async ({ route, file, type }) => [
    route,
    { body: await readFile(file, "utf8"), type },
  ]),
);

const binaryEntries = await Promise.all(
  binaryAssets.map(async ({ route, file, type }) => [
    route,
    { body: (await readFile(file)).toString("base64"), encoding: "base64", type },
  ]),
);

const assets = Object.fromEntries([...sourceEntries, ...binaryEntries]);
const patientQuestionAssistantSource = await readFile(
  "scripts/patient-question-assistant.mjs",
  "utf8",
);
const workerSource = `// Generated by scripts/build.mjs. Source lives in src/.
import {
  patientQuestionAssistantStatus,
  runPatientQuestionAssistant
} from "./patient-question-assistant.mjs";

const assets = ${JSON.stringify(assets)};
const frontierWindows = new Map();
const FRONTIER_WINDOW_MS = 60000;
const FRONTIER_REQUEST_LIMIT = 12;
const baseHeaders = {
  "cache-control": "no-store",
  "content-security-policy": "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'none'; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",
  "permissions-policy": "camera=(), microphone=(), geolocation=()",
  "referrer-policy": "no-referrer",
  "x-content-type-options": "nosniff",
  "x-frame-options": "DENY"
};

function decodeBase64(value) {
  const decoded = atob(value);
  return Uint8Array.from(decoded, (character) => character.charCodeAt(0));
}

function apiHeaders() {
  return {
    "cache-control": "no-store",
    "content-type": "application/json; charset=utf-8",
    "x-content-type-options": "nosniff"
  };
}

function jsonResponse(status, value) {
  return new Response(JSON.stringify(value), { status, headers: apiHeaders() });
}

function environmentFromBindings(env) {
  return {
    OPENAI_API_KEY: typeof env?.OPENAI_API_KEY === "string" ? env.OPENAI_API_KEY : "",
    VITAGRAPH_FRONTIER_ENABLED: env?.VITAGRAPH_FRONTIER_ENABLED === "true" ? "true" : "false",
    VITAGRAPH_FRONTIER_MODEL: typeof env?.VITAGRAPH_FRONTIER_MODEL === "string"
      ? env.VITAGRAPH_FRONTIER_MODEL
      : "gpt-5.6-sol"
  };
}

function assertSameOrigin(request, url) {
  const fetchSite = request.headers.get("sec-fetch-site") || "";
  if (fetchSite && fetchSite !== "same-origin" && fetchSite !== "none") return false;
  const origin = request.headers.get("origin");
  if (!origin) return true;
  try {
    return new URL(origin).origin === url.origin;
  } catch {
    return false;
  }
}

function allowFrontierRequest(request) {
  if (!request.headers.get("origin")) return false;
  const key = request.headers.get("cf-connecting-ip")
    || request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()
    || "unknown";
  const now = Date.now();
  const current = frontierWindows.get(key);
  const next = !current || now - current.startedAt >= FRONTIER_WINDOW_MS
    ? { startedAt: now, count: 1 }
    : { startedAt: current.startedAt, count: current.count + 1 };
  frontierWindows.set(key, next);
  if (frontierWindows.size > 2000) {
    for (const [candidate, window] of frontierWindows) {
      if (now - window.startedAt >= FRONTIER_WINDOW_MS) frontierWindows.delete(candidate);
    }
  }
  return next.count <= FRONTIER_REQUEST_LIMIT;
}

async function patientQuestionApi(request, url, env) {
  if (!assertSameOrigin(request, url)) {
    return jsonResponse(403, { code: "ORIGIN_NOT_ALLOWED", message: "같은 VitaGraph 출처의 요청만 허용합니다." });
  }
  const environment = environmentFromBindings(env);
  if (url.pathname === "/api/patient-question-assistant/status" && request.method === "GET") {
    return jsonResponse(200, patientQuestionAssistantStatus(environment));
  }
  if (url.pathname !== "/api/patient-question-assistant" || request.method !== "POST") {
    return jsonResponse(405, { code: "METHOD_NOT_ALLOWED", message: "지원하지 않는 API 요청입니다." });
  }
  if (!(request.headers.get("content-type") || "").toLowerCase().startsWith("application/json")) {
    return jsonResponse(415, { code: "JSON_REQUIRED", message: "application/json 요청만 허용합니다." });
  }
  const raw = await request.text();
  if (new TextEncoder().encode(raw).byteLength > 256 * 1024) {
    return jsonResponse(413, { code: "PAYLOAD_TOO_LARGE", message: "정제 질문 요청은 256KB 이하여야 합니다." });
  }
  let payload;
  try {
    payload = JSON.parse(raw || "{}");
  } catch {
    return jsonResponse(400, { code: "INVALID_JSON", message: "JSON 요청 형식이 올바르지 않습니다." });
  }
  const provider = payload?.provider === "frontier" ? "frontier" : "local";
  if (provider === "frontier" && payload?.consent !== true) {
    return jsonResponse(400, { code: "FRONTIER_CONSENT_REQUIRED", message: "프론티어 모델 전송 동의가 필요합니다." });
  }
  const status = patientQuestionAssistantStatus(environment);
  if (!status[provider].configured) {
    return jsonResponse(503, {
      code: provider === "frontier" ? "FRONTIER_NOT_CONFIGURED" : "LOCAL_AI_NOT_CONFIGURED",
      message: "규칙 기반 질문을 사용합니다."
    });
  }
  if (provider === "frontier" && !allowFrontierRequest(request)) {
    return jsonResponse(429, {
      code: "FRONTIER_RATE_LIMITED",
      message: "프론티어 질문 요청이 너무 많거나 브라우저 출처를 확인할 수 없습니다. 잠시 후 다시 시도하세요."
    });
  }
  try {
    return jsonResponse(200, await runPatientQuestionAssistant(payload, { environment }));
  } catch (error) {
    if (error instanceof TypeError) {
      return jsonResponse(400, { code: "INVALID_PATIENT_CONTEXT", message: error.message });
    }
    return jsonResponse(502, { code: "PATIENT_MODEL_FAILED", message: "선택한 AI가 유효한 근거 질문을 반환하지 못했습니다." });
  }
}

export default {
  async fetch(request, env = {}) {
    const url = new URL(request.url);
    if (url.pathname.startsWith("/api/patient-question-assistant")) {
      return patientQuestionApi(request, url, env);
    }
    if (url.pathname === "/api/clinical-copilot/status" && request.method === "GET") {
      return jsonResponse(200, { configured: false, mode: "rule-based", model: "" });
    }
    if (url.pathname.startsWith("/api/clinical-copilot")) {
      return jsonResponse(405, {
        code: "METHOD_NOT_ALLOWED",
        message: "공개 빌드는 임상 데이터를 받지 않습니다."
      });
    }
    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method not allowed", {
        status: 405,
        headers: { ...baseHeaders, allow: "GET, HEAD" }
      });
    }

    const route = url.pathname === "/index.html" ? "/" : url.pathname;
    const asset = assets[route];
    if (!asset) {
      return new Response("Not found", { status: 404, headers: baseHeaders });
    }

    const body = request.method === "HEAD"
      ? null
      : asset.encoding === "base64"
        ? decodeBase64(asset.body)
        : asset.body;

    const headers = { ...baseHeaders, "content-type": asset.type };
    if (["/emr", "/emr.html", "/insights", "/insights.html"].includes(route)) {
      headers["content-security-policy"] = headers["content-security-policy"].replace("connect-src 'none'", "connect-src 'self'");
    }
    return new Response(body, {
      headers
    });
  }
};
`;

await rm("dist", { recursive: true, force: true });
await mkdir("dist/server", { recursive: true });
await Promise.all([
  writeFile("dist/server/index.js", workerSource, "utf8"),
  writeFile(
    "dist/server/patient-question-assistant.mjs",
    patientQuestionAssistantSource,
    "utf8",
  ),
]);
console.log("Built dist/server/index.js and its patient question assistant module");
